version: '3'
services:
  weather-app1:
    build:
      context: ./weather-app
      args:
        - VERSION=v2.0
    container_name: weather-app1
    ports:
      - "8080:3000"
    networks:
      - weather_app
    environment:
      - NODE_ENV=production
  weather-app2:
    build:
      context: ./weather-app
      args:
        - VERSION=v2.0
    container_name: weather-app2
    ports:
      - "8081:3000"
    networks:
      - weather_app
    environment:
      - NODE_ENV=production
  weather-app3:
    build:
      context: ./weather-app
      args:
        - VERSION=v2.0
    container_name: weather-app3
    ports:
      - "8082:3000"
    networks:
      - weather_app
    environment:
      - NODE_ENV=production
  nginx:
    build: ./nginx
    container_name: nginx
    tty: true
    ports:
      - '80:80'
    networks:
      - frontend
      - weather_app

networks:
  frontend:
    driver: bridge
  weather_app:
    internal: true
