version: '3.1'
services:
 mydb:
  container_name: testpostgres
  image: postgres:13
  environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
  volumes:
   - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
   - pgdata:/var/lib/pgsql/data
  networks:
   - mybridge2
volumes:
  pgdata:

networks:
  mybridge2:
   driver: bridge
