version: "3"
services:
  db:
    image: postgres:9.4
    container_name: db
    networks:
      - back-tier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "6379"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine3.10
    container_name: redis
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - back-tier
    expose:
      - "6379"
    depends_on:
      - db

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: worker:1.0
    container_name: worker
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - back-tier
    depends_on:
      - db

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    image: result:1.0
    container_name: result
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - front-tier
      - back-tier
    ports:
      - "5001:80"
      - "5858:5858"
    volumes:
      - ./result:/app
    command: nodemon server.js
    depends_on:
      - db

  vote:
    build:
      context: ./vote
      dockerfile: Dockerfile
    image: vote:1.0
    container_name: vote
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - front-tier
      - back-tier
    ports:
      - "5000:80"
    volumes:
      - ./vote:/app
    command: python app.py
    depends_on:
      - db

volumes:
  db-data:

networks:
  back-tier:
    driver: bridge
  front-tier:
    driver: bridge
